### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by forwhatest** [F6JO/RouteVulScan#13]
1、添加分类，建议提供可根据脚本语言的不同对规则进行分类处理，减少不必要的请求
2、添加选择，建议每个规则设置为可选的形式，可自由选择想要的规则，可快速定位漏洞点
3、vuldisplay面板中发现的漏洞url可进行单行或多行复制，字段可进行简单的排序，如vulname和url

**Comment by F6JO** [comment]
111，加入到更新计划，感谢

**Comment by F6JO** [comment]
已更新1、2
