### ISSUE TITLE
yaml规则不能识别

### ISSUE THREAD

**Issue by lightr3d** [F6JO/RouteVulScan#14]
根据yaml文件中的规则自定义了一些规则，点击load后不能正常识别，整个config界面都空白了

**Comment by F6JO** [comment]
你好师傅，截图瞅一眼

**Comment by lightr3d** [comment]
比如这种：
- {re: html, method: GET, name: customer-jeecg, id: 121, state: '200', url: /jeecgFormDemoController.do?commonUpload,  info: maybe upload!!!}
- {re: html, method: POST, name: customer-jeecg, id: 122, state: '200', url: /jeecgFormDemoController.do?commonUpload,  info: maybe upload!!!}

**Comment by F6JO** [comment]
尝试给url加上单引号试一下

**Comment by lightr3d** [comment]
解决了，感谢师傅
