### ISSUE TITLE
burpPro 2022.8.4 加载最新版本插件没有生成VulDisplay界面

### ISSUE THREAD

**Issue by F1echazo** [F6JO/RouteVulScan#16]
本机和拓展环境java版本1.8
burp启动java版本15
加载插件后output正常，没有报错
![image](https://user-images.githubusercontent.com/34188664/205118355-861c273b-feb2-444f-9d35-ddf70c11a6db.png)

**Comment by F6JO** [comment]
你好师傅，是下载的最新的jar包吗，我之前上传错了一个调试版本里面因为调试没有加载VulDisplay界面

**Comment by F1echazo** [comment]
是的，是下载Releases中10月25日提交的版本，而且我本地用jdk11的旧版burp加载插件是可以正常使用的..........
jdk11 启动 burpPro 2020.4.1 正常加载插件；

![image](https://user-images.githubusercontent.com/34188664/205229818-bd4b5c2f-3086-4e02-9b07-bd8a72159a1c.png)

jdk15 启动burpPro 2022.8.4 加载插件无报错，Suite tabs没加载出来；

Extender-Options-Java Environment都是jdk1.8

**Comment by F6JO** [comment]
我试了jdk15和2022.8.4没有问题呀，莫非你说的Suite tabs是这里吗
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/64877810/205235425-267ca921-4829-43c4-9fdd-6eab9c407332.png">

**Comment by F1echazo** [comment]
我的意思是没有这个table ........ sry，没表达清楚
![image](https://user-images.githubusercontent.com/34188664/205235706-fbfc9455-a165-405c-b946-c2d5772a20eb.png)
加载插件后没有生成table，插件的Details能清楚看到Suite tabs没加载出来
如果你的没问题我排查下我 jdk15......
