### ISSUE TITLE
启动插件suite tabls无法加载

### ISSUE THREAD

**Issue by F1echazo** [F6JO/RouteVulScan#18]
启动插件suite tabls无法加载
![image](https://user-images.githubusercontent.com/34188664/218631730-769f1300-56b9-40c9-916f-7ba280505d1f.png)
本地java版本 Java1.8.0_281
burp启动版本 java15

**Comment by F6JO** [comment]
你好师傅，这个问题也有其他人遇到过，一般都是windows，不过这个问题目前还没找到产生的原因，可以尝试更换启动burp的java版本试一下。

**Comment by F1echazo** [comment]
emmmm事实上高版本burp很早之前就出问题了，然后我换回了1.7的burp，但最近也加载不出来了emmmm

**Comment by F6JO** [comment]
> emmmm事实上高版本burp很早之前就出问题了，然后我换回了1.7的burp，但最近也加载不出来了emmmm

方便加个v不

**Comment by chenchenhen6** [comment]
我的也是这种情况，1.3之前能加载出来，1.4也加载不出来，但是1.2是好好的

**Comment by F6JO** [comment]
要不尝试把配置文件Config_yaml.yaml删掉再加载？

**Comment by F6JO** [comment]
是不是单独修改过配置文件，导致加载错误

**Comment by F6JO** [comment]
或者能发一份Config_yaml.yaml吗

**Comment by chenchenhen6** [comment]
我重新删除了Config_yaml.yaml又好了，没有单独配置过文件

**Comment by F6JO** [comment]
应该是版本切换导致配置文件不兼容的原因

**Comment by chenchenhen6** [comment]
感谢大佬帮我解决问题

**Comment by chenchenhen6** [comment]
/ueditor/net/controller.ashx?action=catchimage
/Content/plugins/ueditor/net/controller.ashx?action=catchimage
/Utility/UEditor/net?action=catchimage
/Utility/UEditor?action=catchimage
/scripts/ueditor/net/controller.ashx?action=catchimage
/js/ueditor/net/controller.ashx?action=catchimage
/Static/ueditor/net/controller.ashx?action=catchimage
/Scripts/Ueditor/net/controller.ashx?action=catchimage
大佬是否能将这些路径默认加载在配置文件里，我每次更新都更没了

**Comment by F1echazo** [comment]
....确实很可能是配置文件的问题，我删掉配置文件后现在加载suitetable也没问题了

**Comment by F6JO** [comment]
> /ueditor/net/controller.ashx?action=catchimage /Content/plugins/ueditor/net/controller.ashx?action=catchimage /Utility/UEditor/net?action=catchimage /Utility/UEditor?action=catchimage /scripts/ueditor/net/controller.ashx?action=catchimage /js/ueditor/net/controller.ashx?action=catchimage /Static/ueditor/net/controller.ashx?action=catchimage /Scripts/Ueditor/net/controller.ashx?action=catchimage 大佬是否能将这些路径默认加载在配置文件里，我每次更新都更没了

好的 正则有没有呀，还有1.4版本已经修改在线更新为追加而不是覆盖了

**Comment by chenchenhen6** [comment]
还没正则，哈哈哈我都是直接加，主要是有时候会遇到.net ueditor文件上传

**Comment by chenchenhen6** [comment]
^\/(ueditor|Content\/plugins\/ueditor|Utility\/UEditor|scripts\/ueditor|js\/ueditor|Static\/ueditor)\/net\/controller\.ashx\?action=catchimage$
不知道这个正则可以不，还没测试
