### ISSUE TITLE
主动扫描的问题

### ISSUE THREAD

**Issue by ZzzZodn** [F6JO/RouteVulScan#19]
首先感谢作者提供了这么好的插件，但用下来主动扫描发现了点bug

如果打开bp后直接使用主动扫描，logger中既不会出现请求，插件的Errors和Output中也没有任何输出

如果先通过被动扫描，扫描了路径/aa/bb/cc/dd/。然后再使用主动扫描的方式，扫描/a/b/c/d/e/，logger中没有找到插件发出的扫描请求，插件的Errors中输出了多个Skip，如下图。
<img width="674" alt="image" src="https://user-images.githubusercontent.com/89087285/219836998-9cb9de5d-8dc8-4beb-92e9-a96e6495b4e0.png">

PS：可以修改一下VulDisplay面板的请求和响应的分隔位置吗，每次都得手动调整到中间。

BP版本：2021.4.1

**Comment by F6JO** [comment]
你好师傅，解释一下哈
主动扫描是根据Target里的目标和路径扫描的，因为插件是根据已有的路径进行探测，不会主动去探测路径，所以打开burp的时候target里没有目标所以才没有进行扫描。
而打印Skip是因为这个路径已经由插件探测过了，所以跳过不扫描，为了减少请求的个数。
另外那个请求和响应我会抽时间瞅瞅改一下。

**Comment by ZzzZodn** [comment]
明白了，是我理解错这个主动扫描了，感谢师傅~
