### ISSUE TITLE
Config_yaml.yaml配置文件生成失败

### ISSUE THREAD

**Issue by wwsuixin** [F6JO/RouteVulScan#2]
burpsuite pro版本为v2022.3.9  使用的java版本为java17

初次装载插件会在burpsuite当前目录下生成Config_yaml.yaml配置文件，内置11条初始规则，也可在config标签页自行加载其他yaml规则文件。
![image](https://user-images.githubusercontent.com/62787020/172976530-40d9c440-bb59-490f-9db5-42120f67d55b.png)
装载插件时未生成config_yaml.yaml配置文件

手动创建config_yaml.yaml文件 使用add功能也没有反应
![image](https://user-images.githubusercontent.com/62787020/172977019-f1a8e601-eef9-4110-b5cc-b3db087dc2dc.png)

请问这个是java版本的原因吗

**Comment by F6JO** [comment]
这个报错看起来是Config_yaml.yaml文件没有生成成功，可以看一下burp目录下是否有Config_yaml.yaml文件，如果有的话删掉文件再加载插件试试

**Comment by F6JO** [comment]
> burpsuite pro版本为v2022.3.9 使用的java版本为java17
> 
> 当前配置插件会在burpsuite的Config_yaml配置文件，包含目录11条生成初始规则，在config标签自己页加载yaml规则文件。还有其他可 时未生成config_ml.yaml配置文件 ![图片](https://user-images.githubusercontent.com/62787020/172976530-40d9c440-bb59-490f-9db5-42120f67d55b.png)
> 
> 手动创建config_yaml.yaml文件 使用添加功能也没有反应 ![图片](https://user-images.githubusercontent.com/62787020/172977019-f1a8e601-eef9-4110-b5cc-b3db087dc2dc.png)
> 
> 这是java版本的原因吗？

把yaml文件删除再重新加载插件试试，如果还有问题的话，可以加我微信讨论一下
![image](https://user-images.githubusercontent.com/64877810/172980995-c8679b3c-96fd-4db2-a6ab-7b13da8a35d7.png)
