### ISSUE TITLE
建议增加白名单机制

### ISSUE THREAD

**Issue by Vicl1fe** [F6JO/RouteVulScan#20]
建议增加白名单，可自定义白名单域名，白名单的域名不进行扫描。例如baidu.com google.com等。有时候测的域名和ip太多，不想一个一个填FIlter_host，建议增加白名单

**Comment by kingz40o** [comment]
+1
https://github.com/vaycore/OneScan
类似项目的这个的黑白名单配置可以考虑加上

**Comment by F6JO** [comment]
好的加入到更新计划

**Comment by F6JO** [comment]
此处可通过burp自带的功能进行配置，先不加了
<img width="790" alt="image" src="https://user-images.githubusercontent.com/64877810/236664163-f6ede180-6667-403a-a0ce-8d9b45525fc6.png">
<img width="878" alt="image" src="https://user-images.githubusercontent.com/64877810/236664185-7c373276-bb01-4b72-8ab2-3d8b15b3f132.png">
