### ISSUE TITLE
将主域和子域当作第一层路径默认扫描，这个功能能不能变为可选

### ISSUE THREAD

**Issue by lightr3d** [F6JO/RouteVulScan#23]
想直接扫描自定义的字典，不想将主域和子域当作第一层路径默认扫描。希望下个版本将这个功能设置为可选

**Comment by F6JO** [comment]
只不过多了一个或两个请求而已，没必要关掉吧

**Comment by lightr3d** [comment]
或者把优先级改一下呢，先扫默认路径，然后再将主域和子域当作第一层路径默认扫描。如果遇到waf场景，扫第一波后就会禁ip了，导致想直接扫根目录的路径还没扫到就被封了

**Comment by F6JO** [comment]
好的 下个版本加个选项吧

**Comment by F6JO** [comment]
已更新1.5
