### ISSUE TITLE
添加排除路径

### ISSUE THREAD

**Issue by JaveleyQAQ** [F6JO/RouteVulScan#26]
login delete这种操作每次都得先关了操作完了才能启动，像是login允许重发时候就会导致登陆被顶，还有一下download包，没有必要浪费资源去请求

**Comment by JaveleyQAQ** [comment]
另外ui能不能适配一下随窗口缩放🙃 按钮文字显示不全

**Comment by F6JO** [comment]
第一个问题可以参考一下我刚加的说明"推荐使用方式"。第二个已加入更新计划。
