### ISSUE TITLE
burp 2022.9.6 使用bug

### ISSUE THREAD

**Issue by jielansudo** [F6JO/RouteVulScan#28]
我目前版本使用工具，使用一段时间就会导致burp卡死，具体原因不太清楚，但是确实存在相关问题。

**Comment by F6JO** [comment]
可能是burp时间开太长了？插件每请求一个url就会把路径记在内存里

**Comment by JackQian123** [comment]
不是，我是202207版本的burp，确实一会就会卡死

**Comment by F6JO** [comment]
更新了1.5.1，增加了超时跳过，可能会解决此问题
