### ISSUE TITLE
使用的问题

### ISSUE THREAD

**Issue by yinjunll** [F6JO/RouteVulScan#29]
当我在配置文件里加一条匹配记录，访问方法为GET，路径为/druid/index.html，并做好返回页面的正则，如：www.baidu.com/druid/index.html 存在未授权，我输入www.baidu.com并开启抓包，RouteVulScan的vuldisplay并未展示这条记录，不知道什么原因，大佬有时间麻烦解惑一下

**Comment by F6JO** [comment]
可以排查一下logger页面的请求记录，然后在响应中匹配一下正则以及响应码看看是否能匹配到
