### ISSUE TITLE
Burp2023.6.1版本无法使用

### ISSUE THREAD

**Issue by CHINA-china** [F6JO/RouteVulScan#34]
点击update没有反应，更新不了规则

**Comment by F6JO** [comment]
是访问github自动更新，需要配置一下顶级代理翻墙
<img width="1006" alt="image" src="https://github.com/F6JO/RouteVulScan/assets/64877810/61592239-ed8e-4812-951d-418e191d8237">

**Comment by CHINA-china** [comment]
好的谢谢，以及能更新规则了，但是似乎无法使用，我是用SpringScan能扫描出swagger-ui，使用RouteVulScan却没反应
![image](https://github.com/F6JO/RouteVulScan/assets/92798047/f6030940-74d1-4ce7-9be7-13910507c942)
![image](https://github.com/F6JO/RouteVulScan/assets/92798047/36b76da0-6045-4f85-a676-78ec7d2bf04e)
![image](https://github.com/F6JO/RouteVulScan/assets/92798047/4ee58af8-12ec-4c12-b221-4a9cc450eed7)

**Comment by CHINA-china** [comment]
问题已解决，谢谢
