### ISSUE TITLE
师傅扫描时自动跳过了/目录是什么问题?DomainScan开启了

### ISSUE THREAD

**Issue by lanqingaa** [F6JO/RouteVulScan#35]
![cc278a83fda831cac2c86b26776bf61](https://github.com/F6JO/RouteVulScan/assets/94030940/60a6ca8b-f0c5-46e9-b3ef-400c67f5df04)
![1a84be7ca5636346c6d4e1803bcb409](https://github.com/F6JO/RouteVulScan/assets/94030940/499faeeb-b61f-4fd2-9228-04636278848b)
![cba7d2aac4f56ab951ba383406f829d](https://github.com/F6JO/RouteVulScan/assets/94030940/f5b990b5-257e-4649-85e5-b2463b333191)

**Comment by F6JO** [comment]
应该是有判断这个路径已经请求过了，最新的规则里把这个删掉了，在线更新只会追加，可以下载覆盖一下 。
