### ISSUE TITLE
修改配置文件工具出现崩溃

### ISSUE THREAD

**Issue by perkupup** [F6JO/RouteVulScan#38]
burpsuite版本2021.8.1，在bp里面修改配置信息的时候，工具出现崩溃，无法运行，并且关闭bp后再打开时routevul栏目直接消失了。只有将原本的Config_yaml文件删除，将备份的Config_yaml替换进来才能恢复。

**Comment by F6JO** [comment]
高版本插件没法适配低版本的配置文件奥
