### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jinzezhi** [F6JO/RouteVulScan#40]
重定向后才能访问的资产的无法捕获到
例如 http://test.com/decision     后面加上decision路径才会跳转到帆软的数据决策系统，给RouteVulScan加的规则为匹配路径：/decision 
 响应码200  ，不会自动重定向，就失去了这条资产。
 
 另外 加不上师傅微信

**Comment by F6JO** [comment]
看看有空加个重定向按钮

**Comment by F6JO** [comment]
好像直接匹配对应302或者3xx的响应头然后内容匹配Location的值即可？
如果需要每条规则添加一个选项是否跟随302，需要修改配置文件的格式，会破坏各个版本兼容。
so 这条先往后排
