### ISSUE TITLE
配置了代理，update也没有响应

### ISSUE THREAD

**Issue by xss-root** [F6JO/RouteVulScan#42]
配置了代理，update也没有响应

**Comment by F6JO** [comment]
我这边是正常的，看一下logger里是否有请求
<img width="1014" alt="image" src="https://github.com/F6JO/RouteVulScan/assets/64877810/c32a0a18-4680-437e-bf1f-b6b3f3f062c5">

**Comment by xss-root** [comment]
logger日志里面没有请求，是怎么回事呢，网络代理的问题

**Comment by F6JO** [comment]
应该是网络的问题 github挂上burp 然后burp挂代理看看能不能访问

**Comment by handbye** [comment]
同样的问题，logger里也没看到请求，挂了代理可以访问github

**Comment by handbye** [comment]
> 同样的问题，logger里也没看到请求，挂了代理可以访问github

重启burp问题解决
