### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jinjiao070** [F6JO/RouteVulScan#46]
bypass规则中，似乎没有spring相关的这个 /..;/..;/  这一条，建议师傅添加一下吧

**Comment by F6JO** [comment]
bypass故意没设置太多的 因为请求会成倍增长，如果有需求的话 可以直接在配置文件里加
<img width="764" alt="image" src="https://github.com/F6JO/RouteVulScan/assets/64877810/115a2029-eadd-4da2-a121-e3751bfb1472">
