### ISSUE TITLE
无法触发路径扫描

### ISSUE THREAD

**Issue by YHUldAQc** [F6JO/RouteVulScan#48]
之前有段时间使用还算正常。现在重新测试时完全没有结果：
![image](https://github.com/F6JO/RouteVulScan/assets/77220883/b52a764c-b2fd-4721-95b3-0ee0eb56d928)
测试了两个版本，结果一致。
![image](https://github.com/F6JO/RouteVulScan/assets/77220883/7103998e-0f69-4a0f-9fbd-08068359ab74)

**Comment by F6JO** [comment]
今天优化了面板添加的规则，之前是重复的url直接过滤掉，现在不再拦截重复的url。不知道是不是这个原因才导致结果不显示。

**Comment by YHUldAQc** [comment]
我是本地起一个python3的http服务，然后使用浏览器访问，在服务端观察访问的请求路径。
观察结果来看，是插件没有生效，应该不是有重复URL的问题。

在BApp Store下载的旧版插件可以触发扫描，而Release下的近两个版本都无法触发。
我目前使用的JDK21 环境下的BurpSuite v2024.2.1。

> 今天优化了面板添加的规则，之前是重复的url直接过滤掉，现在不再拦截重复的url。不知道是不是这个原因才导致结果不显示。
