### ISSUE TITLE
Bypass问题

### ISSUE THREAD

**Issue by aHlo666** [F6JO/RouteVulScan#50]
正常扫描一个地址如：http://x.x.x.x:80/abc/，扫描配置文件中spring的 /actuator/env
不加Bypass时扫描路径为：http://x.x.x.x:80/abc/actuator/env
而使用Bypass功能后，扫描路径是在每个 / 后面都添加Bypass_List中的字符
http://x.x.x.x:80/./abc/./actuator/./env
http://x.x.x.x:80/%2e/abc/%2e/actuator/%2e/env
这样导致原本可以访问的http://x.x.x.x:80/abc/，变成http://x.x.x.x:80/%2e/abc/不能访问了。
不是应该只在扫描地址和配置文件中的url之间加Bypass字符吗？
比如：http://x.x.x.x:80/abc/%2e/autuator/env
![image](https://github.com/F6JO/RouteVulScan/assets/67671500/a50c2df0-5f21-4844-bf5b-1abd8b45b712)

**Comment by F6JO** [comment]
好像是哦 下个版本改

**Comment by F6JO** [comment]
师傅能加个v讨论下不？F6JO-MAC

**Comment by F6JO** [comment]
已更新1.5.2
