### ISSUE TITLE
The load plug-in is not displayed 加载插件不显示

### ISSUE THREAD

**Issue by HuangLiyulu** [F6JO/RouteVulScan#51]
![image](https://github.com/F6JO/RouteVulScan/assets/40757958/e651aa68-bd10-487d-af9c-50c6d21f287f)
加载Route vulnerable Scan 不显示
![image](https://github.com/F6JO/RouteVulScan/assets/40757958/5ab353d0-9292-49ef-8eff-4b28f37b5746)

**Comment by HuangLiyulu** [comment]
重装bp好了

**Comment by F6JO** [comment]
其实应该是配置文件的问题，把插件的配置文件删了再加载就可以了
