### ISSUE TITLE
使用了2022版本的BP安装最新版本插件后，无法更新配置文件，看不到任何规则

### ISSUE THREAD

**Issue by Superhero-zero** [F6JO/RouteVulScan#53]
![image](https://github.com/F6JO/RouteVulScan/assets/66772820/3e0c9e76-9569-447d-ab01-036494de36df)

**Comment by F6JO** [comment]
有没有使用代理

**Comment by Superhero-zero** [comment]
> 有没有使用代理

关了跟开了两个都试了，点击update没有任何反应

**Comment by F6JO** [comment]
怎么设置的代理截个图瞅一眼

**Comment by Superhero-zero** [comment]
> 怎么设置的代理截个图瞅一眼

开了小飞机全局代理

**Comment by F6JO** [comment]
需要配置burp的顶级代理
<img width="831" alt="image" src="https://github.com/F6JO/RouteVulScan/assets/64877810/1a0b484d-bfb2-454e-adb9-17137b05965d">

**Comment by Superhero-zero** [comment]
> 需要配置burp的顶级代理 <img alt="image" width="831" src="https://private-user-images.githubusercontent.com/64877810/312286389-1a0b484d-bfb2-454e-adb9-17137b05965d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTcxMjYsIm5iZiI6MTcxMDI5NjgyNiwicGF0aCI6Ii82NDg3NzgxMC8zMTIyODYzODktMWEwYjQ4NGQtYmZiMi00NTRlLWFkYjktMTcxMzdiMDU5NjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMGI3ZGE1OTk2MWU4ZGY0MTU2MThhMjZiYzBlYWY4MGRhOTJlMDNkNjBhNDljYjk2OTI0NDlmZjJkZTNjOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zbv308ltb4mv-Fsm6KyqpnMn8uhuZUFv7aNCTB4nBkE">

![image](https://github.com/F6JO/RouteVulScan/assets/66772820/7d84df75-7dba-49e7-b160-45e810c6e74d)
![image](https://github.com/F6JO/RouteVulScan/assets/66772820/fa5b04ac-b3c8-44d1-bf9f-bb673f408022)

**Comment by F6JO** [comment]
估计还是代理的问题，你也可以手动下载https://github.com/F6JO/RouteVulScan/blob/main/Config_yaml.yaml
然后覆盖到这个地方
<img width="488" alt="image" src="https://github.com/F6JO/RouteVulScan/assets/64877810/c336f9fe-03ea-4d34-a90d-130acff5566c">

**Comment by Superhero-zero** [comment]
> 估计还是代理的问题，你也可以手动下载https://github.com/F6JO/RouteVulScan/blob/main/Config_yaml.yaml 然后覆盖到这个地方 <img alt="image" width="488" src="https://private-user-images.githubusercontent.com/64877810/312290970-c336f9fe-03ea-4d34-a90d-130acff5566c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTMzNzAsIm5iZiI6MTcxMDMxMzA3MCwicGF0aCI6Ii82NDg3NzgxMC8zMTIyOTA5NzAtYzMzNmY5ZmUtMDNlYS00ZDM0LWE5MGQtMTMwYWNmZjU1NjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA2NTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhOGQyMzYxMjc1YWQxZjJkMTM3MjI5NTEwNWU2MTU3ZTA3NzQ5ZTdmNDA0NDE2MzZkNGJhYzEyYzNlODYzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BzDekpFlGpXHkzCTeAYh_1Y80d3xvBG3LWs5-_mYwiU">

自己手动覆盖了，但是在测试的似乎似乎出了一点问题，无论是主动还是被动，插件都接收不到
![image](https://github.com/F6JO/RouteVulScan/assets/66772820/6da3c29d-3272-48bc-86dd-c135f095ae2f)
![image](https://github.com/F6JO/RouteVulScan/assets/66772820/5b871d12-560e-4e9c-b120-e079b043888b)
![image](https://github.com/F6JO/RouteVulScan/assets/66772820/afa95b01-0ac7-49af-a172-20c3e2a560c3)

**Comment by Superhero-zero** [comment]
> 估计还是代理的问题，你也可以手动下载https://github.com/F6JO/RouteVulScan/blob/main/Config_yaml.yaml 然后覆盖到这个地方 <img alt="image" width="488" src="https://private-user-images.githubusercontent.com/64877810/312290970-c336f9fe-03ea-4d34-a90d-130acff5566c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTM3NzEsIm5iZiI6MTcxMDMxMzQ3MSwicGF0aCI6Ii82NDg3NzgxMC8zMTIyOTA5NzAtYzMzNmY5ZmUtMDNlYS00ZDM0LWE5MGQtMTMwYWNmZjU1NjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA3MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNGE4NjA3MjBjZDNmZDY1ZGE1ZjdkODM0ZTg3NTFjYzRhZmFhNjA4ZTdjOGNlZTc5NzA1ZDk0MDRmZDZhM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KAcwvikqrgztQaGQ3_zzOdBvIG23Lo1H9yA-mjFNGMU">

好的，已覆盖能看到规则
