### ISSUE TITLE
建议增加策略.git/.svn./.DS_Store

### ISSUE THREAD

**Issue by ppofp** [F6JO/RouteVulScan#6]
建议增加策略.git/.svn./.DS_Store

**Comment by F6JO** [comment]
好，多谢师傅

**Comment by F6JO** [comment]
有无详细点的正则、状态码这样的 师傅，因为我试了你说的几个路径，感觉误报很高呢

**Comment by ppofp** [comment]
- {re: .git, method: GET, name: Git, id: 17, state: '200', url: /.git/HEAD, info: .git
    Find!!!}
- {re: Svn, method: GET, name: Svn, id: 18, state: '200', url: /.svn/, info: .svn
    Find!!!}
- {re: ds_store, method: GET, name: DS_Store, id: 19, state: '200', url: /.DS_Store/,
  info: .DS_Store Find!!!}
- {re: README.md, method: GET, name: Git, id: 20, state: '206', url: /README.md, info: README.md
    Find!!!}
- {re: crossdomain.xml, method: GET, name: crossdomain, id: 21, state: '200', url: /crossdomain.xml,
  info: crossdomain.xml Find!!!}
- {re: .idea, method: GET, name: idea, id: 22, state: '200', url: /.idea/modules.xml,
  info: .idea Find!!!}
- {re: readme.txt, method: GET, name: readme, id: 23, state: '206', url: /readme.txt,
  info: readme.txt Find!!!}

**Comment by ppofp** [comment]
> 有没有详细点的正状态、码这样的师傅，则因为我试了你的几个路径，感觉报错呢

- {re: .git, method: GET, name: Git, id: 17, state: '200', url: /.git/HEAD, info: .git
    Find!!!}
- {re: Svn, method: GET, name: Svn, id: 18, state: '200', url: /.svn/, info: .svn
    Find!!!}
- {re: ds_store, method: GET, name: DS_Store, id: 19, state: '200', url: /.DS_Store/,
  info: .DS_Store Find!!!}
- {re: README.md, method: GET, name: Git, id: 20, state: '206', url: /README.md, info: README.md
    Find!!!}
- {re: crossdomain.xml, method: GET, name: crossdomain, id: 21, state: '200', url: /crossdomain.xml,
  info: crossdomain.xml Find!!!}
- {re: .idea, method: GET, name: idea, id: 22, state: '200', url: /.idea/modules.xml,
  info: .idea Find!!!}
- {re: readme.txt, method: GET, name: readme, id: 23, state: '206', url: /readme.txt,
  info: readme.txt Find!!!}

**Comment by F6JO** [comment]
好滴
