### ISSUE TITLE
新版本burpsuite无法显示插件

### ISSUE THREAD

**Issue by JordanANDJohn** [F6JO/RouteVulScan#66]
java版本："21.0.3" 2024-04-16 LTS
burpsuite版本：2024.5.5
只看到加载成功的消息，没有面板显示
![image](https://github.com/user-attachments/assets/55d09533-4e34-4b88-aa7f-950499267a61)

**Comment by F6JO** [comment]
尝试删掉原本的配置文件再重新加载？

**Comment by JordanANDJohn** [comment]
我刚刚试了下，删除burp suite目录下面的配置文件再重新加载还是不行，JDK8和11的JAR文件都试了，都不行。生成的配置文件截图在下面。
![image](https://github.com/user-attachments/assets/6bcee8a8-5818-4ff6-8dd5-14d4b4983e79)

历史数据包里面也可以发送到插件，但就是在上面的标签看不到插件的选项，View那里也没有进行隐藏。我遇到好几个老的插件都有这个问题，HAE在这个版本下面是可以正常用的。
![image](https://github.com/user-attachments/assets/774a4d02-fb6d-42a4-8165-21fc5b1e621f)

**Comment by F6JO** [comment]
师傅使用新jdk编译一下？

**Comment by JordanANDJohn** [comment]
不行的，报错了，我解决不了
![image](https://github.com/user-attachments/assets/e3add12a-93e7-4353-8f10-00603b50ba14)

**Comment by F6JO** [comment]
build.gradle使用这个配置：https://github.com/F6JO/RouteVulScan/blob/main/build.gradle
然后双击此处，多点击几次，编译好的在build的libs下。
<img width="728" alt="image" src="https://github.com/user-attachments/assets/8c497bc9-d004-4999-bfed-343d037ccb3e">

**Comment by JordanANDJohn** [comment]
下载源代码的文件替换成你说的这个也不行，我那个地方加载不了源代码，都是空白的
![image](https://github.com/user-attachments/assets/a7cfe8ad-7118-48ef-a36f-5e5d8476b797)

**Comment by F6JO** [comment]
师傅加个V讨论下 F6JO-MAC
