### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by vectorxiong** [F6JO/RouteVulScan#9]
用的burp20220501版本的，加载插件后，把请求消息发送到RouteVulScan后，插件没办法自动扫描啊？

**Comment by F6JO** [comment]
你好，可以看看extender的Output和Errors是否输出了扫描的路径。右键发送到插件后，会把当前站点地图中所有与当前请求一样host的所有路径全部扫一遍，如果在发送之前被动扫描过，那么会打印在Errors里且不会进行重复扫描
